version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - redis
    ports:
      - "8010:8010"
    working_dir: /var/www/html
    command: php artisan serve --host=0.0.0.0 --port=8010

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis_prog_paralela
    ports:
      - "6379:6379"
    restart: always

  queue:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_queue
    volumes:
      - .:/var/www/html
    depends_on:
      - redis
    working_dir: /var/www/html
    command: php artisan queue:work --verbose --tries=3 --timeout=90

volumes:
  mysql_data:
